# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install ncat
      run: sudo apt-get update && sudo apt-get install -y ncat

    - name: End to end bash test
      run: cd tests/end-to-end/bash; bash two_clients_join.sh

    - name: Dotnet tests
      run: cd tests/Server.Tests; dotnet test
